name: flutter_project
description: A Flutter project with Appwrite SDK

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^13.0.0
  cupertino_icons: ^1.0.2
  # State management
  flutter_riverpod: ^2.5.1
  # Animations and UI
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  dynamic_color: ^1.7.0
  glassmorphism_ui: ^0.3.0
  chat_bubbles: ^1.6.0
  animated_text_kit: ^4.2.2
  emoji_picker_flutter: ^2.2.0
  # Audio and recording
  record: ^5.1.2
  audioplayers: ^6.0.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  # File operations and PDF
  file_picker: ^8.1.2
  pdf: ^3.11.1
  printing: ^5.13.2
  # Search and utilities
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true