@echo off
echo 🔧 Adding environment variables to Trading Post site via CLI...
echo Site ID: 689cb415001a367e69f8

echo.
echo ➕ Adding NODE_ENV...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key NODE_ENV --value production

echo ➕ Adding REACT_APP_APPWRITE_ENDPOINT...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_APPWRITE_ENDPOINT --value https://nyc.cloud.appwrite.io/v1

echo ➕ Adding REACT_APP_APPWRITE_PROJECT_ID...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_APPWRITE_PROJECT_ID --value 689bdaf500072795b0f6

echo ➕ Adding REACT_APP_APPWRITE_DATABASE_ID...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_APPWRITE_DATABASE_ID --value recursion_chat_db

echo ➕ Adding REACT_APP_APPWRITE_USERS_COLLECTION_ID...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_APPWRITE_USERS_COLLECTION_ID --value "Trading Post Users"

echo ➕ Adding REACT_APP_APPWRITE_ITEMS_COLLECTION_ID...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_APPWRITE_ITEMS_COLLECTION_ID --value "Trading Post Items"

echo ➕ Adding REACT_APP_APPWRITE_TRADES_COLLECTION_ID...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_APPWRITE_TRADES_COLLECTION_ID --value "Trading Post Trades"

echo ➕ Adding REACT_APP_APPWRITE_MESSAGES_COLLECTION_ID...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_APPWRITE_MESSAGES_COLLECTION_ID --value "Trading Post Messages"

echo ➕ Adding REACT_APP_APPWRITE_REVIEWS_COLLECTION_ID...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_APPWRITE_REVIEWS_COLLECTION_ID --value "Trading Post Reviews"

echo ➕ Adding REACT_APP_APPWRITE_WANTS_COLLECTION_ID...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_APPWRITE_WANTS_COLLECTION_ID --value "Trading Post Wants"

echo ➕ Adding REACT_APP_APPWRITE_NOTIFICATIONS_COLLECTION_ID...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_APPWRITE_NOTIFICATIONS_COLLECTION_ID --value "Trading Post Notifications"

echo ➕ Adding REACT_APP_APPWRITE_PROFILE_IMAGES_BUCKET_ID...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_APPWRITE_PROFILE_IMAGES_BUCKET_ID --value profile_images

echo ➕ Adding REACT_APP_APPWRITE_ITEM_IMAGES_BUCKET_ID...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_APPWRITE_ITEM_IMAGES_BUCKET_ID --value profile_images

echo ➕ Adding REACT_APP_USE_APPWRITE_AUTH...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_USE_APPWRITE_AUTH --value true

echo ➕ Adding REACT_APP_USE_APPWRITE_DATABASE...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_USE_APPWRITE_DATABASE --value true

echo ➕ Adding REACT_APP_USE_APPWRITE_STORAGE...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_USE_APPWRITE_STORAGE --value true

echo ➕ Adding REACT_APP_USE_APPWRITE_REALTIME...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_USE_APPWRITE_REALTIME --value true

echo ➕ Adding REACT_APP_USE_APPWRITE_FUNCTIONS...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_USE_APPWRITE_FUNCTIONS --value true

echo ➕ Adding REACT_APP_API_URL...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_API_URL --value https://tradingpost.appwrite.network

echo ➕ Adding REACT_APP_GOOGLE_SSO_ENABLED...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_GOOGLE_SSO_ENABLED --value true

echo ➕ Adding REACT_APP_EMAIL_ENABLED...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_EMAIL_ENABLED --value true

echo ➕ Adding REACT_APP_PUSH_NOTIFICATIONS_ENABLED...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key REACT_APP_PUSH_NOTIFICATIONS_ENABLED --value true

echo ➕ Adding GENERATE_SOURCEMAP...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key GENERATE_SOURCEMAP --value false

echo ➕ Adding CI...
appwrite sites create-variable --site-id 689cb415001a367e69f8 --key CI --value false

echo.
echo ✅ All environment variables added!
echo 🔄 Trigger a redeploy in the Appwrite console to apply changes.
pause