# Comprehensive Security Configuration Suite
# Based on Agent Swarm Security Analysis

security:
  # Authentication Configuration
  authentication:
    jwt:
      algorithm: "RS256"
      access_token_ttl: 900  # 15 minutes
      refresh_token_ttl: 604800  # 7 days
      issuer: "recursionsystems.com"
      audience: ["api", "web", "mobile"]
      
    password_policy:
      min_length: 8
      require_uppercase: true
      require_lowercase: true
      require_numbers: true
      require_special_chars: true
      max_age_days: 90
      history_count: 5
      
    session:
      secure: true
      http_only: true
      same_site: "strict"
      max_age: 86400  # 24 hours
      
    rate_limiting:
      login_attempts:
        window_minutes: 15
        max_attempts: 5
        lockout_duration: 900  # 15 minutes
      password_reset:
        window_minutes: 60
        max_attempts: 3
      email_verification:
        window_minutes: 60
        max_attempts: 5

  # API Security
  api:
    rate_limiting:
      global:
        window_minutes: 15
        max_requests: 1000
      per_endpoint:
        "/api/auth/login":
          window_minutes: 15
          max_requests: 10
        "/api/auth/register":
          window_minutes: 60
          max_requests: 5
        "/api/chat/messages":
          window_minutes: 15
          max_requests: 100
        "/api/trades":
          window_minutes: 15
          max_requests: 50
          
    cors:
      allowed_origins:
        - "https://chat.recursionsystems.com"
        - "https://tradingpost.appwrite.network"
        - "https://slumlord.appwrite.network"
        - "https://archon.appwrite.network"
        - "https://localhost:3000"  # Development only
      allowed_methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
      allowed_headers:
        - "Content-Type"
        - "Authorization"
        - "X-Requested-With"
        - "X-API-Key"
      credentials: true
      max_age: 86400
      
    input_validation:
      max_payload_size: "10MB"
      content_types:
        - "application/json"
        - "multipart/form-data"
        - "application/x-www-form-urlencoded"
      sanitization:
        html: true
        sql_injection: true
        xss: true
        path_traversal: true

  # Data Protection
  data_protection:
    encryption:
      algorithm: "AES-256-GCM"
      key_rotation_days: 90
      
    pii_fields:
      - "email"
      - "phone"
      - "address"
      - "payment_info"
      - "ssn"
      - "license_number"
      
    data_retention:
      user_data_days: 2555  # 7 years
      session_data_days: 30
      log_data_days: 365
      audit_trail_days: 2555  # 7 years
      
    gdpr_compliance:
      enabled: true
      consent_required: true
      data_portability: true
      right_to_deletion: true
      privacy_policy_url: "/privacy-policy"
      cookie_consent: true

  # Security Headers
  headers:
    strict_transport_security:
      max_age: 31536000
      include_subdomains: true
      preload: true
      
    content_security_policy:
      default_src: "'self'"
      script_src: "'self' 'unsafe-inline' https://cdn.jsdelivr.net"
      style_src: "'self' 'unsafe-inline' https://fonts.googleapis.com"
      font_src: "'self' https://fonts.gstatic.com"
      img_src: "'self' data: https:"
      connect_src: "'self' https://nyc.cloud.appwrite.io"
      frame_ancestors: "'none'"
      
    other_headers:
      x_frame_options: "DENY"
      x_content_type_options: "nosniff"
      x_xss_protection: "1; mode=block"
      referrer_policy: "strict-origin-when-cross-origin"
      permissions_policy: "geolocation=(), microphone=(), camera=()"

  # Monitoring & Alerting
  monitoring:
    failed_logins:
      threshold: 10
      window_minutes: 5
      alert_channels: ["email", "slack"]
      
    unusual_activity:
      multiple_locations: true
      rapid_requests: true
      privilege_escalation: true
      
    security_events:
      log_level: "INFO"
      retention_days: 365
      real_time_alerts: true
      
    vulnerability_scanning:
      enabled: true
      schedule: "daily"
      severity_threshold: "medium"
      auto_patch: false

  # Compliance
  compliance:
    frameworks:
      - "SOC 2 Type II"
      - "GDPR"
      - "CCPA"
      
    audit_logging:
      enabled: true
      events:
        - "authentication"
        - "authorization"
        - "data_access"
        - "data_modification"
        - "system_changes"
        - "security_events"
        
    backup_encryption: true
    data_classification:
      public: []
      internal: ["user_preferences", "app_settings"]
      confidential: ["user_data", "payment_info"]
      restricted: ["api_keys", "encryption_keys"]

# Environment-Specific Overrides
environments:
  development:
    security:
      headers:
        content_security_policy:
          script_src: "'self' 'unsafe-inline' 'unsafe-eval'"
      api:
        cors:
          allowed_origins:
            - "http://localhost:3000"
            - "http://localhost:3001"
            - "http://localhost:8080"
            
  staging:
    security:
      authentication:
        rate_limiting:
          login_attempts:
            max_attempts: 10  # More lenient for testing
            
  production:
    security:
      authentication:
        session:
          secure: true
          same_site: "strict"
      headers:
        strict_transport_security:
          preload: true
      monitoring:
        real_time_alerts: true