name: Deploy to Appwrite Static Hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build web
      run: flutter build web --release --web-renderer canvaskit
    
    - name: Create deployment package
      run: |
        cd build/web
        tar -czf ../../deployment.tar.gz .
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: flutter-web-build
        path: deployment.tar.gz
    
    - name: Deploy notification
      run: |
        echo "✅ Build complete!"
        echo "📦 Deployment package created"
        echo "🚀 Ready for manual deployment to Appwrite"
        echo ""
        echo "To deploy:"
        echo "1. Download the artifact from GitHub Actions"
        echo "2. Extract to your Appwrite static hosting directory"
        echo "3. Configure routing to serve index.html"